const KEY='recovery-v3';
const seed={version:12,weight:200.8,goal:163,calGoal:1750,proGoal:120,fasting:false,selectedDay:5,notes:'',checks:{walk:false,strength:false,water:false,sleep:false},weights:[{date:'2026-09-14',value:205},{date:'2026-09-18',value:200.8}],training:[],meals:[
{id:101,day:1,name:'Protein bread + turkey',detail:'2 slices protein bread, about 5 slices turkey, lettuce/salad',kcal:330,protein:34},
{id:102,day:1,name:'Injera + tibs dinner',detail:'Injera, beef/tibs, salad, cottage cheese, small doro wot, awaze',kcal:760,protein:43},
{id:201,day:2,name:'Zucchini + leftovers',detail:'Zucchini, tibs/beef, drumstick and couscous',kcal:560,protein:40},
{id:202,day:2,name:'Homemade dabo',detail:'Almond flour + dark Ethiopian bread flour',kcal:180,protein:6},
{id:203,day:2,name:'Chili plate',detail:'Chili, egg, split peas, drumstick, cottage cheese, greens',kcal:690,protein:47},
{id:301,day:3,name:'Tofu + carrots + dabo',detail:'Tofu, carrots and homemade dabo',kcal:430,protein:24},
{id:302,day:3,name:'Chickpea pasta + lentils',detail:'Chickpea rotini, lentils, mixed vegetables, diced tomatoes with green chilies, small BBQ sauce and sriracha; 1 tbsp psyllium',kcal:610,protein:31},
{id:303,day:3,name:'Apple + peanut butter',detail:'Chopped apple with cinnamon and measured peanut butter',kcal:220,protein:4},
{id:401,day:4,name:'Leftover legume bowl + sardines',detail:'Leftover chickpea pasta/lentil/vegetable mix, cooked grain and lightly smoked sardines',kcal:650,protein:45},
{id:402,day:4,name:'Homemade tuna sub',detail:'Toasted multigrain bread, tuna, light mayo, cottage cheese, chopped salad, tomato, seasoning and a little butter',kcal:575,protein:40},
{id:501,day:5,name:'Yellow split-pea + chickpea bowl with sardines',detail:'Leftover yellow split peas/legumes with chickpeas added today, plus one sardine serving',kcal:600,protein:35},
{id:502,day:5,name:'Tofu scramble + tuna bowl',detail:'Tofu scramble, 1 drained can tuna, a few legumes, shredded salad and 3 croutons',kcal:575,protein:55}
]};
const foods={tuna:{name:'Tuna crunch bowl',detail:'Tuna in water + large salad + light dressing',kcal:350,protein:35},chicken:{name:'Chicken vegetable plate',detail:'Chicken breast + vegetables + small starch portion',kcal:500,protein:45},fast:{name:'Fasting protein bowl',detail:'Tofu + lentils + vegetables + measured oil',kcal:500,protein:30},sub:{name:'Tuna sub',detail:'Multigrain bread + tuna + light mayo + cottage cheese + vegetables',kcal:575,protein:40},sardine:{name:'Sardine legume bowl',detail:'Legumes/chickpeas + sardines + vegetables',kcal:600,protein:42},cottage:{name:'Cottage cheese plate',detail:'Low-fat cottage cheese + vegetables + protein bread',kcal:380,protein:35}};
const routines={A:[['Leg press','3 × 8–12'],['Chest press','3 × 8–12'],['Lat pulldown','3 × 8–12'],['Seated row','2 × 10–12'],['Hamstring curl','2 × 10–15'],['Plank','2 sets']],B:[['Goblet squat / leg press','3 × 8–12'],['Incline press','3 × 8–12'],['Cable row','3 × 8–12'],['Shoulder press','2 × 8–12'],['Calf raise','2 × 12–15'],['Dead bug','2 sets']],H:[['Goblet squat','3 × 10'],['DB bench press','3 × 8–12'],['One-arm row','3 × 10/side'],['DB Romanian deadlift','3 × 10'],['DB shoulder press','2 × 10'],['Plank','2 sets']]};
let state=JSON.parse(localStorage.getItem(KEY)||'null');if(!state||state.version<12){state=JSON.parse(JSON.stringify(seed));localStorage.setItem(KEY,JSON.stringify(state))}let routineKey='A';const $=q=>document.querySelector(q),save=()=>localStorage.setItem(KEY,JSON.stringify(state));function dm(d=state.selectedDay){return state.meals.filter(x=>x.day===d)}function total(ms){return ms.reduce((a,x)=>({k:a.k+(+x.kcal||0),p:a.p+(+x.protein||0)}),{k:0,p:0})}function meal(x,del=false){return '<div class="meal"><div class="grow"><strong>'+x.name+'</strong><span class="sub">'+x.detail+'</span><span class="tag">~'+x.kcal+' kcal · ~'+x.protein+'g protein</span></div>'+(del?'<div><button class="btn small" onclick="editMeal('+x.id+')">Edit</button> <button class="btn small" onclick="removeMeal('+x.id+')">Remove</button></div>':'')+'</div>'}
function render(){const t=total(dm());$('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});$('#fast').textContent=state.fasting?'☦ Fasting day':'Regular day';$('#cal').textContent='~'+t.k;$('#pro').textContent='~'+t.p+'g';$('#calLeft').textContent=Math.max(0,state.calGoal-t.k)+' kcal remaining';$('#proLeft').textContent=Math.max(0,state.proGoal-t.p)+'g remaining';$('#calBar').style.width=Math.min(100,t.k/state.calGoal*100)+'%';$('#proBar').style.width=Math.min(100,t.p/state.proGoal*100)+'%';$('#weight').textContent=state.weight+' lb';$('#todayMeals').innerHTML=dm().map(x=>meal(x)).join('')||'<p class="sub">No meals yet.</p>';document.querySelectorAll('[data-check]').forEach(b=>b.classList.toggle('done',!!state.checks[b.dataset.check]));
$('#days').innerHTML=[1,2,3,4,5,6,7].map(d=>'<button class="tab '+(d===state.selectedDay?'active':'')+'" onclick="selectDay('+d+')">Day '+d+'</button>').join('');$('#dayTotal').textContent='Day '+state.selectedDay+' · ~'+t.k+' kcal · ~'+t.p+'g protein';$('#mealList').innerHTML=dm().map(x=>meal(x,true)).join('')||'<p class="sub">No meals logged.</p>';$('#quickFoods').innerHTML=Object.entries(foods).slice(0,4).map(([k,x])=>'<div class="food"><b>'+x.name+'</b><span class="sub">'+x.protein+'g protein · ~'+x.kcal+' kcal</span><br><button class="btn small" onclick="quickMeal(\''+k+'\')">Add</button></div>').join('');
const week=state.training;$('#workouts').textContent=week.length;$('#minutes').textContent=week.reduce((n,x)=>n+x.mins,0);$('#trainingHistory').innerHTML=week.slice().reverse().map(x=>'<div class="meal"><div class="grow"><strong>'+x.name+'</strong><span class="sub">'+x.date+' · '+x.mins+' min</span></div></div>').join('')||'<p class="sub">No workouts logged yet.</p>';renderRoutine();
const all=total(state.meals),days=new Set(state.meals.map(x=>x.day)).size||1,avgK=Math.round(all.k/days),avgP=Math.round(all.p/days),lost=205-state.weight;$('#trendStats').innerHTML='<div class="mini"><b>'+lost.toFixed(1)+'</b><span class="sub">lb down</span></div><div class="mini"><b>~'+avgK+'</b><span class="sub">kcal/day</span></div><div class="mini"><b>~'+avgP+'g</b><span class="sub">protein/day</span></div>';barChart('#weightChart',state.weights.map(x=>({v:x.value,l:x.date.slice(5)})),190,206);barChart('#calChart',[1,2,3,4,5,6,7].map(d=>({v:total(dm(d)).k,l:'D'+d})),0,1800);barChart('#proChart',[1,2,3,4,5,6,7].map(d=>({v:total(dm(d)).p,l:'D'+d})),0,120);$('#notes').value=state.notes||'';$('#mealLibrary').innerHTML=Object.entries(foods).map(([k,x])=>'<div class="food"><b>'+x.name+'</b><span class="sub">'+x.detail+'</span><span class="tag">'+x.protein+'g protein · ~'+x.kcal+' kcal</span><br><button class="btn small" onclick="quickMeal(\''+k+'\')">Add to Day '+state.selectedDay+'</button></div>').join('')}
function barChart(sel,data,min,max){$(sel).innerHTML=data.map(x=>'<div class="col"><div class="stick" style="height:'+Math.max(3,Math.min(120,(x.v-min)/(max-min)*120))+'px"></div><small>'+x.l+'</small></div>').join('')}
function renderRoutine(){$('#routine').innerHTML=routines[routineKey].map((x,i)=>'<div class="exercise"><b>'+x[0]+'</b><div class="sub">'+x[1]+'</div><div class="sets"><button class="set" onclick="this.classList.toggle(\'done\')">Done</button></div></div>').join('')}
window.go=(v,e)=>{document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');document.querySelectorAll('.nav span').forEach(x=>x.classList.remove('active'));e.classList.add('active');render()};window.selectDay=d=>{state.selectedDay=d;save();render()};window.toggleFast=()=>{state.fasting=!state.fasting;save();render()};window.toggleCheck=k=>{state.checks[k]=!state.checks[k];save();render()};window.showRoutine=(k,e)=>{routineKey=k;document.querySelectorAll('#trainingView .tab').forEach(x=>x.classList.remove('active'));e.classList.add('active');renderRoutine()};window.finishWorkout=()=>{const mins=Number(prompt('Workout minutes',40)||0);if(!mins)return;state.training.push({id:Date.now(),name:routineKey==='H'?'Home workout':'Gym '+routineKey,mins,date:new Date().toISOString().slice(0,10)});state.checks.strength=true;save();render()};window.logWeight=()=>{const v=Number(prompt('Weight (lb)',state.weight));if(!v)return;state.weight=v;state.weights.push({date:new Date().toISOString().slice(0,10),value:v});save();render()};window.quickMeal=k=>{let x=foods[k];state.meals.push({id:Date.now(),day:state.selectedDay,...x});save();render()};window.addMeal=()=>{let name=prompt('Meal');if(!name)return;let detail=prompt('What was in it?')||'',kcal=Number(prompt('Estimated calories')||0),protein=Number(prompt('Estimated protein (g)')||0);state.meals.push({id:Date.now(),day:state.selectedDay,name,detail,kcal,protein});save();render()};window.editMeal=id=>{let x=state.meals.find(m=>m.id===id);if(!x)return;let name=prompt('Meal',x.name);if(!name)return;x.name=name;x.detail=prompt('What was in it?',x.detail)||'';x.kcal=Number(prompt('Estimated calories',x.kcal)||x.kcal);x.protein=Number(prompt('Estimated protein (g)',x.protein)||x.protein);save();render()};window.removeMeal=id=>{state.meals=state.meals.filter(x=>x.id!==id);save();render()};window.saveNotes=v=>{state.notes=v;save()};window.exportData=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='recovery-backup.json';a.click()};window.importData=()=>{let i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{let r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render()}catch{alert('Could not read backup')}};r.readAsText(i.files[0])};i.click()};render();